version: '3.1'

services:
    web:
        build: .
        environment: 
            DATABASE_URI: mysql+mysqlconnector://root:root@database/production_ready
            SECRET_KEY: 'development_testing_local_key'
        ports:
            - 5000:5000
        depends_on:
            - database

    database:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: production_ready
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
