name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Install dependencies and Deploy to AWS
      run: |
        pip install virtualenv
        virtualenv --python=python3.7 --system-site-packages venv
        source venv/bin/activate
        pip install -r requirements/deploy.txt
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_KEY }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET }}"
        export AWS_DEFAULT_REGION="${{ secrets.REGION }}"
        export PRODUCTION="True"
        zappa update
